core/urls.py
from django.urls import path 
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('new_expense', views.new_expense, name='new_expense')
]

expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.register, name='register'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name 
    
    class Meta:
        verbose_name_plural = 'Categories'
    
class Expense(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    amount = models.BigIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self) -> str:
        return self.name 

users/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from .models import Category, Expense
from django.db.models import Sum
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    categories = []
    _categories = Category.objects.all()
    for category in _categories:
        total_expenditure = category.expense_set.filter(owner=request.user).aggregate(Sum('amount'))['amount__sum'] or 0
        categories.append({
            'category': category,
            'total_expenditure': total_expenditure
        })

    expenses = Expense.objects.filter(owner=request.user).order_by('-date')
    context = { 'categories': categories, 'expenses': expenses }
    return render(request, 'core/index.html', context)

@login_required
def new_expense(request):
    res = { 'message': '' }
    code = 200
    if request.method == 'POST':
        _category = request.POST['category']
        category = Category.objects.filter(name=_category).first()
        name = request.POST['name']
        amount = request.POST['amount']
        date = request.POST['date']
        try:
            new_expense = Expense.objects.create(category=category, amount=amount, name=name, date=date, owner=request.user)
        except Exception:
            res['message'] = 'Failed to create new expense!'
            code = 500
        else:
            res['message'] = 'New expense successfully created'
        return JsonResponse(res, status=code)

users/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth import login 
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            print("New user")
            new_user = form.save()
            login(request, new_user)
            return redirect('core:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

core/templates/core/index.html
{% load static %}
{% load intcomma %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expense Tracker</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="{% static 'js/new_expense.js' %}"></script>
    <script src="{% static 'js/transaction.js' %}"></script>
</head>

<body>
    <div class="success" style="display: none;">
        <svg style="width: 30px; height: auto;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>check-circle</title><path fill="#006400" d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" /></svg>
        <p class="title">
            Success
        </p>
        <p class="message">Successfully created a new expense</p>
    </div>
    <div class="body">
        <div class="navbar">
            <div class="logo">Expense.io</div>
            <div class="profile">
                {% if user.is_authenticated %}
                    <img src="{% static 'images/profile.jpg' %}" alt="profile">
                    <p class="username">
                        {{ user.username }}
                    </p>
                    <a href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'users:register' %}">Register</a>
                    <a href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
        <div class="main">
            <div class="sidebar">
                <div class="tile">
                    <svg style="width: 30px; height: auto;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <title>view-dashboard-outline</title>
                        <path
                            d="M19,5V7H15V5H19M9,5V11H5V5H9M19,13V19H15V13H19M9,17V19H5V17H9M21,3H13V9H21V3M11,3H3V13H11V3M21,11H13V21H21V11M11,15H3V21H11V15Z" />
                    </svg>
                    <span>Dashboard</span>
                </div>
                <p class="copy">All rights reserved Group 5</p>
            </div>
            <div class="categories">
                {% for category in categories %}
                    <div class="category">
                        <p class="name">{{ category.category.name }}</p>
                        <p class="total">
                            UGX
                            <span>{{ category.total_expenditure|intcomma }}</span>
                        </p>
                    </div>
                {% endfor %}
            </div>
            <div class="aside">
                <div class="header">
                    <svg style="width: 30px; height: auto;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <title>wallet-bifold-outline</title>
                        <path
                            d="M15.5 15.5C16.33 15.5 17 14.83 17 14C17 13.17 16.33 12.5 15.5 12.5C14.67 12.5 14 13.17 14 14C14 14.83 14.67 15.5 15.5 15.5M7 3H17C18.11 3 19 3.9 19 5V7C20.11 7 21 7.9 21 9V19C21 20.11 20.11 21 19 21H7C4.79 21 3 19.21 3 17V7C3 4.79 4.79 3 7 3M17 7V5H7C5.9 5 5 5.9 5 7V7.54C5.59 7.2 6.27 7 7 7H17M5 17C5 18.11 5.9 19 7 19H19V9H7C5.9 9 5 9.9 5 11V17Z" />
                    </svg>
                    <span>Your Transaction History</span>
                </div>
                <div class="transactions">
                    {% for expense in expenses %}
                        <div class="transaction">
                            <div class="icon">
                            </div>
                            <div class="details">
                                <p class="name">{{ expense.name|safe }}</p>
                                <p class="date">{{ expense.date|safe }}</p>
                                <p class="category" hidden>{{ expense.category|escape }}</p>
                            </div>
                            <p class="value">
                                UGX
                                <span>{{ expense.amount|intcomma }}</span>
                            </p>
                        </div>
                    {% endfor %}
                </div>
                <div class="footer">
                    <button class="new">Add New</button>
                </div>
            </div>
        </div>
    </div>
    <div class="newExpenseContainer" style="display: none;">
        <div class="new_expense">
            <p>New Expense</p>
            <p class="error" style="display: none;">
                Failed to create the new record!
            </p>
            <form method='POST' action="{% url 'core:new_expense' %}" id="expense-form">
                {% csrf_token %}
                <select name="category" required>
                    <option value="Groceries">Groceries</option>
                    <option value="Utilities">Utilities</option>
                    <option value="Transportation">Transportation</option>
                    <option value="Entertainment">Entertainment</option>
                    <option value="Food">Food</option>
                </select>
                <input type="text" name="name" placeholder="Name" id="name" required>
                <input type="number" name="amount" placeholder="Amount" id="amount" required>
                <input type="date" name="date" id="date" required>
                <div class="buttons">
                    <input type="button" value="Cancel" id="cancel">
                    <input type="submit" value="Add Expense" id="new">
                </div>
            </form>
        </div>
    </div>
</body>

</html>